apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-values
  namespace: storage
type: Opaque
stringData:
  values.yaml: |
    csiDriver:
      name: org.democratic-csi.iscsi

    node:
      kubeletHostPath: /var/lib/kubelet

    storageClasses:
      - name: truenas-iscsi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        mountOptions: []
        parameters:
          fsType: ext4

    volumeSnapshotClasses: []

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: production-truenas-iscsi

        httpConnection:
          protocol: https
          host: fs.turtleware.au
          port: 443
          apiKey: REPLACE_WITH_TRUENAS_API_KEY
          allowInsecure: false

        zfs:
          datasetParentName: BigSpeed/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: BigSpeed/k8s/iscsi/s
          zvolCompression: lz4
          zvolDedup: off
          zvolEnableReservation: false
          datasetEnableQuotas: true

        iscsi:
          targetPortal: fs.turtleware.au:3260
          targetPortals: []
          interface: default
          namePrefix: csi-
          nameTemplate: "{{ name }}"
          extentInsecureTpc: true
          extentBlocksize: 4096
          extentDisablePhysicalBlocksize: true
          extentRpm: SSD
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 2
