apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
  namespace: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw
  template:
    metadata:
      labels:
        app: draw
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      containers:
        - name: draw
          image: excalidraw/excalidraw:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: development
            - name: TIMEZONE
              value: Australia/Sydney
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
