apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  valuesFrom:
    - kind: Secret
      name: headlamp-oidc-values
      valuesKey: values.yaml
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 12h
  values:
    fullnameOverride: headlamp
    replicaCount: 1
    config:
      inCluster: true
      inClusterContextName: main
      enableHelm: true
      extraArgs:
        - -oidc-skip-tls-verify
        - -oidc-use-access-token
      oidc:
        scopes: openid,profile,email,offline_access
        usePKCE: true
    serviceAccount:
      create: true
      name: headlamp
    clusterRoleBinding:
      create: false
    service:
      type: ClusterIP
      port: 80
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
