apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-values
    namespace: headlamp
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:/mtlALJuHVWmhRKwp3kzxCkcje9XmAgeDI/8zcNomdvtBGBesQV8lJJ9lZea5/QumQHfD9MpZTJZPveyRV0zGZyEPJv8aekZonEFHlFwrWtBJWJKiHPDC/KELohTeqaR49FjiEV+I1AbrR1OVawmAd49d7li57DpzRlSBs/wh8Slj+s1+HQcnVWFA96+HQxHtA+uJxWYgDShp/kYXFWQ5T0nwpxrPRwsKIXQebq6VRfM3dqm0clxxTls5z4cUT8ej3MQfa4HMNil5j5Jo104OptEqUCc0+tXd9RGyrNX+AJb3r5yxZDsLv55mhcirBvVmsgephR2GKQv10D1zrLPoVwrAkfrkQQ/Zwoqmj36mQrT5iISTV3X1iO+tol+FprFysXFNcdaEyjqFoeBXLsR5ThTp6OEHp+KO1zSbwmGFKEq64mvdKd7StSAzydW81bqmbYmgOi4TD9D/Qvl53ID3WJmrhKcPvHiIPYAQI1vtjV+C1IgcxlmXVdAwDLiLf/8nw91jIK3fvuHRgF2hUkQ,iv:xAX4hTSJmqQ7mOIAkxMm/M2y6ZaWMCqRP5lYrG7ITEs=,tag:QXpr9Xtb555oUZ7em0ckZw==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL0g5Z1VtMmdqc1RSSXFr
            OWg3OHlTdGp1WVZMblMxQWo0cE9qSVV5bnk4CjF5LzlKQ2prQnFHSFQvY0JNcTNG
            akRiSllYYW8yRmR2ZHQ3ZDhmaFlQTzQKLS0tIHdtSUdIZE13djNLN1NaZXVSQStU
            enQyVnBLRk5QTkdiQ2RJN0JlRGt0TkkK7udz4eE228yMNoaRVwvgVPKtxJscrXsl
            GzaPqcvemY3aXke6oeJx2Xjxtrus/fMjblwsu6A1TTxm0491JQp2VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T05:42:25Z"
    mac: ENC[AES256_GCM,data:1vd7JyIvpkToQOtB/FWoVEw/0AxMf/MJT38MmJbxxCg4RbpXzo/1ETHmQ7hjhtBbN2Rdn5c0a7eGk2mEJf0PeSCS7W1Wc7wE8y0Bhp0BIaDaMdQaXHGGenxPSl3/QfBHndjSzKwF0WEikqVssvhjZb4C8WZGvex2kpUXmMQTCVY=,iv:pIa8RTwJTQt7s6iFcmfY+9se3G6Jl57biqZwxbAHSBk=,tag:mkNHQstL1v3sOFBfxr6wcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
