apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-values
    namespace: headlamp
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:JPRm4TaYWLmmUVnk3KofHYBSI7zVfMZ2HamGV/3kzJMcWTxLB+cisS6lTakhdscCqtxI/SJ8fo5ZuEnQgvbSLTOBsVGxGOrgVdw+0LZOI8q0wYtWrMQz0YOeBUu48YpxCfqAvJ15ks8Gi3VaL6e9cDYGQNcZ235izuLTrZKE/rsV9KwbtP+WE2vxXqAfHWqtVsJPXdQB7iKHF8wsuv+dQwrqjwL3m3zBG/7fksNDuDg4Q80CW9bjxAY9iPhZN3Ubg7ZRsfmxKJJf5sDsTGekkxYgqAx4saSg3TSCl/+5oHQCcP3RA2PPO+6Tq4H+RI9OSUBagpeQ6WKjq4Q4WE6zntAqm0gtF6oZVlrGbjQj6GOn5NsLy3leED9xyffEfGtQ0HKglf5F4l6kz2FK1gsgFwXABAsgEpyYLyb1G431320fLmWawlnfelrM/9ztnVG/wMlbZ2O9SNrwJV61FQXT1fsJeIlorAX1hQaDrgsdWe6mABPi2QEXMdp9HUjPqtrTYXLbtnbLDl73hmehVOcmdIVoykdWNPSWxnXFGVBk9y1aw4pbE4AP8X1T5EA=,iv:GUEzGuLre/fdnGSV1ST3SuV2NLcOjZq6fh+4V3im/gI=,tag:t+FHmdZckM9e8CiVfxMIiQ==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISFI1NWphQzJmYkM0eUts
            K3hEM0Z0VXBSNEdKajVKUUo3UWJFUXRzaEdnCjFVL3Q2YmI2UEQyZzRBaXE5aldD
            dU9KNVFrbTRNVkcwcWNRVU5RdXdmTW8KLS0tIFlSc1hPcjdWaEdINVoyYm9hc3Bw
            UHRFN2NrRGtUQVRNdWNpbm9HS0ZOVEUK2r7i8XsWP552Jwj6KmATwuIhxMC9B5s6
            mlAkr7KM/CHfPWnmi57vuDm6XrqPE3vFBMT6GMwVVdJ70b1eWWa17w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T05:46:54Z"
    mac: ENC[AES256_GCM,data:yYhHud2n/T2jUm6FZi8kXTNd4W+BqZz96zzHkIdeR8Ns6EwyHCZhfF+G6vSc24riEKslEQ4TBlb287TSEcf8GXTWN7M0TyIVT1ICV1XnhQz5VSToKKfAx0RF8Fg/yl9jswsqD9k2tOYZv+1Wa1IcFnzGFbdYo/mJzkeNoBkvhFA=,iv:5WWNKoHNnuM2Dg50sZvIOMh95LbH3JQX5HjVRjpOXI4=,tag:MYBGlzsSlb0gCq5Ig3mmEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
