apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-values
    namespace: headlamp
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:qOb68hIGWKd6rYYcfZW+6PjhuxsuMHhnp9mN3U+ndryGY5MgLIIX9AWvjQXw+EcfGVMiFrF8w0pKHNF+h07O86R+zFbly1rZQ9fDuqQZkhncS+rd93Fup7dcFQd5yIC5T0uhKdshXQCqqaeF0pEm1UAPxWRVHmZfo9OatNxoxQbAWz5twaRAr3+JbG8i18H1a/TkqlnMc23jrIuIjs5Fkm9bihxl30T6mFfIpAoQ9OzDoNdclNJ+G/B91pgayA8pnlvRvlODaXYlQsqSR9ZtdWUmOvIQTFYmPrf1insmI74xUhvrr2VBKBWc7IPlYsWe+Xb+sKCO2WM3odYUDUcUwiTWy6zkM4scIH5IPtLm85F9qC2QaWe9QMzqp2X+HHh8SKCU7zx5/7frzkDsGkahNeBzhTD88pci08e7DhEdOKp8pJ8HdnoRBQ==,iv:dEAX2Sah8CWICWyBb/NTfyige1FY+XWlA/tSqdDiT9s=,tag:manWH2ZGG/M6pBliHIdb9w==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWUswL25Fb3M4QlB3WldV
            c08vZzJjU0VoUWllV3ZlcGd2YzdBdFRQVGgwCmFBZ3F5ZjREYmZ3S1ZFOEVwU3BS
            VXJpRW1ML1ZVdUNiODBkd0p4ZnNmU3cKLS0tIFlPQ0ZBSzUySjlzdW9jTjlnMjRV
            UFJ4R2dyenpiZWpJL1FLamVTV3hvNDgKR/6XozcMF/B1di2ClRBEVWzQQ8RUYclb
            cxgu29Fwkebuv4d21x40kLb8xnagsu0/rkU5fdnV185LJg4hps7quw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T05:13:06Z"
    mac: ENC[AES256_GCM,data:LnYDpN3KBTce8ZbsAGwiHOSG05m80n7HfrMAtmAqtNqXdseJtCQOEVa0Wz8vSa23wWmPGOkVemb03jg8aa1oKD2QpGNPiI36Mg+jAAxgNCfTON4cLsvU+JFgqmWuxTUt10lZE2oX2dgipB3N/Z4QAvoau5FUvzSXHZvwqTnVfek=,iv:/cED3k9/te7KxM7V09bPkln7J9sTAMUoOTuL/wMhI+g=,tag:LhX1XBsAQpiUVG4m45S5Rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
