apiVersion: v1
kind: Secret
metadata:
    name: reflection-env
    namespace: reflection
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:koKNfA==,iv:xOdoqYEQmVS9at6eQjeJlcrv1II6UVT7ZsaHOTeT7To=,tag:tdQvQi4U7TONCsmCnTNXbw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:VyENc+3IYmiVSlpBgsdw+krK/Q==,iv:lKkGGnPawLpfRwIEeTJvamE2ETM3ckz2BLps4eYqkWE=,tag:a6QINfHVfnnPZBzQ9a5qmg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:vQUgQA==,iv:nF4Mg6suBxXZ+MXHi5e3HzANQDcdPbcMM9GEgWzNLNQ=,tag:GTD/PjcFCzhXC/HHf8aaRw==,type:str]
    REDIS_USERNAME: ""
    REDIS_PASSWORD: ENC[AES256_GCM,data:hWiF4leeqYRN8ogwclPQo01/E9WZORO/gSRffxteGrM=,iv:L3rIvJgD1waCPOVZMzQ7dztbevwXFRy4/9nEouPw1ok=,tag:3BskXrf1md35cuUbSmcBgQ==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:2iyw5gdtbgu6uXV6fDKQGdF2rM/dty1et8M34bxifojkwtkp+Ug9Qw==,iv:ZXjtxFNDL3bWHQmm7yUwzNvCymvCXKgWoMwZBzu+q5M=,tag:NwjFnXCHOfX13yqri4dcUw==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:8R/HBYll7hxzWG2UqOrxTfVlxnKkWgMqgfF3vLL9czqpQdLdtdHG19fNqwszLPLMBQ5WLO+X0gUpwSZk6PmccO5K0BZPLfNfNaY7gpfTgXsi9N4/syr5HZ3P2wbkJb9VUgdEUJL12nSfyBu/rDnwKsGnpZJOzLmzkZD59K+wixU=,iv:GRpRPgjf33nmJ+x00+H//imXa7HViRF2Dm9Z4zBy+D4=,tag:8tBBZfan+kntl4WD7w9O8Q==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:Eyzxli6TZ42KGmBjbli7jqI0qhDInTDQ1T9QErzjRJA=,iv:xeaWDONLi6zFXV22rVlWoKC8CQsqvFfG/S3vAlLVrr0=,tag:4zN91/i61asek3UmUBkFIg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:5HRNBDcyEKyeaqCn9xBuPmvwdxr/NQO0kdVLQFr4nEY=,iv:U41uENGk53thOeqRloBX4M0hPXsOTnDA6oiciW0AC2I=,tag:BfK9QE5LWc9f/Torf4y+kA==,type:str]
    REFLECTIONS_API_URL: ENC[AES256_GCM,data:FN2tPd5+TzCmEyWP91FYvSj6fxMMOXqqh1QL0+U=,iv:RRkwKUlAQTFCosXrSF0oobBg+L9U34+UBaTZ3lqJxDc=,tag:/gk4T5Uu+pAYCf3iZOLMGA==,type:str]
    REFLECTIONS_API_KEY: ENC[AES256_GCM,data:MYY8mszc8HSyrKHTztiGPbRdzgoeGUeOWyrhdbEzp8NV+D0QfSVqByPi+my0b4YRnGU6nHaOva39Z+reguXm4A==,iv:3F4yDgtuSNyWI+FJ0ryh+x+nDmKjxkhP9q39v2mUMrQ=,tag:W22CkCIYMBdKEFnBnpqgCA==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2dlK0RSbWdHTmVsSlFs
            SEZNaER4Vk1KRkVPMlVKR3E3dWorT3h5ZWpzCkxTOG9pbjVaTnZBWkI2cDczVDQ3
            R1RTME54bnNpT1lmZ29VOVZGd0gyRVUKLS0tIDdMdTQ4RDFKUEJDWTdwOXVqc29R
            bmFHaDZta09peDVOQzF4S3pkUVJPUmcKTmAh0q3HKHiyZhlaelk7iSGahhAbtnnx
            547VMt90rLv59u96zSyQkjV/UVtxdoG0gFkI9JF6g4VLmmYGtapayQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T03:05:09Z"
    mac: ENC[AES256_GCM,data:aFvkZWo0mviR0/47nrWfJ4KDmYGMtsZ6Vmvpye954y+eXtyMBtKg7J5UCcwt4qt5AW5ObDnBdtZVvZDEKfX8yS5nQbQq5FHRNMa6G7B5x/AP4U9tjl8ajcmDEbpRSDS6/2gpdDiZMCGL9vgjCRig+R04RttrZZ/IbE8KuZ+hc58=,iv:bEvx9Z117l6pjCtEzT9wtnSx0F1rHDbu4qHp8WGjhz8=,tag:Q+WMZCAad75Dtc2RtAiewA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
