apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: usage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: usage
  filterTags:
    pattern: "^master_(?P<ts>[0-9]{14})_[a-f0-9]+$"
    extract: "$ts"
  policy:
    numerical:
      order: asc
