apiVersion: v1
kind: Secret
metadata:
    name: usage-env
    namespace: usage
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:WBnh1ihyvMGIE5s=,iv:cAVaGxLzL4QJMQab3/4dwkDzBYY9+DFyFmnTP5Hz0Dg=,tag:qBAKqFhpLCExgwKLkusmxA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:wsTvGw==,iv:VMtnBDEKtHkJdQxx8BiA8x5zJUWs8SUhg18WRzbH1PY=,tag:d3N5p03CkIOu1ziT1jHoVA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:nmLSaMvGsg==,iv:qO+PJ+5lF96FeyGLe68k44X6Qp1Po5EtHZAO9PdE/bE=,tag:MCM4s8QXdXULCxAKIo9XSg==,type:str]
    DB_USER: ENC[AES256_GCM,data:1+Ou6pfoaw==,iv:4WRoHp+exM+sZX9tDzLLTEIKyight4Q8aRVZD1ZCxJs=,tag:VDv7tIF68ZoitCHoeYaxlQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:lPEFTd1h8LeSZQtv6L7ZG37hA6Ja+4jt/SpdQeZseZ4=,iv:H1A7MOHwdXkoXh8h+pXZkQKbFKlOeHkZcEHffw5e/eM=,tag:aGwiJk8dyYwzShj5JXXnSA==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT1FpT2J5US91RUJFc0Vy
            S21PNEtYTlVGRHo1MW9aRUl1NXBVNVhUZ2tFCkVhV1VEVkF2WEp2b2lET3RPWGNM
            TldVMnVJWTdJZE1XOGV4dFU0cVdyVm8KLS0tIGhCQmt3U1B5aGZjNEExQWlhZ0pG
            ZG4rN3BsUkcvdXFGZ2U5RU5tVTRoUHMKowYEnYJHdEVBHYZANfJAyGNEQXfMNKqY
            zFi42grD7+OFbySVF03tLkHOP4Zr1LGIM6NSgqWpCNrm97GlPnbVkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T11:23:58Z"
    mac: ENC[AES256_GCM,data:Hi9glhsfVbu9yxOlvTDe+rbgJiIIDB6sbCCXgLMkztT3AIQipaYzIyZiEc6HCbk05fJPOJMyBLbMXNamzz0ccISo/Z4AmQxLLCRaFMHxT6V4cHOtcUdCalsB3m9Jxu5bONpPdqFnlQ51/sbhzaWQ8yUO7DWGnvO+BqN9Cstq8ro=,iv:UEupoqAEOnDlW3Jwk9VU44c3t4hxEM21tlCdWYHvC7c=,tag:2+0Ipixd3lLV0OkxhpBhBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
