apiVersion: v1
kind: Secret
metadata:
    name: usage-env
    namespace: usage
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:WBnh1ihyvMGIE5s=,iv:cAVaGxLzL4QJMQab3/4dwkDzBYY9+DFyFmnTP5Hz0Dg=,tag:qBAKqFhpLCExgwKLkusmxA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:wsTvGw==,iv:VMtnBDEKtHkJdQxx8BiA8x5zJUWs8SUhg18WRzbH1PY=,tag:d3N5p03CkIOu1ziT1jHoVA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:nmLSaMvGsg==,iv:qO+PJ+5lF96FeyGLe68k44X6Qp1Po5EtHZAO9PdE/bE=,tag:MCM4s8QXdXULCxAKIo9XSg==,type:str]
    DB_USER: ENC[AES256_GCM,data:1+Ou6pfoaw==,iv:4WRoHp+exM+sZX9tDzLLTEIKyight4Q8aRVZD1ZCxJs=,tag:VDv7tIF68ZoitCHoeYaxlQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jYS7t33ps7SraVg9JG2Aeg8QskZmJXaK+RoOqqyPHYc=,iv:8M3AsfwtryxQFE7GPR5nhSjtqtmTayu1mFRWkTFLvOM=,tag:svuiL3cksv9sbIPX2aA9Sg==,type:str]
    API_KEY: ENC[AES256_GCM,data:vOwOYaFlwIXODwgr32tTErFYwdfs260ExLB0MQ/mMuw=,iv:bR0B7MLNeN6kuKJAt/szwWvBLLTXqSsnAP68H2oCiLY=,tag:kZk0frCKF7sH6Db/kW2k9g==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT1FpT2J5US91RUJFc0Vy
            S21PNEtYTlVGRHo1MW9aRUl1NXBVNVhUZ2tFCkVhV1VEVkF2WEp2b2lET3RPWGNM
            TldVMnVJWTdJZE1XOGV4dFU0cVdyVm8KLS0tIGhCQmt3U1B5aGZjNEExQWlhZ0pG
            ZG4rN3BsUkcvdXFGZ2U5RU5tVTRoUHMKowYEnYJHdEVBHYZANfJAyGNEQXfMNKqY
            zFi42grD7+OFbySVF03tLkHOP4Zr1LGIM6NSgqWpCNrm97GlPnbVkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T11:10:43Z"
    mac: ENC[AES256_GCM,data:IF8ZB3gztswEQi/KV7Sz6kn68DhdNRQbHCAqq4Yhx2W5yegjaZGAIOZOlUlx7DFj7vv2KkHYmgIDH2lxZSvOYmgz/gFvJOP09wPIjfoS5AWawYA4w3Upke+Vm9m15Hx2mTuOTzlkce4iyFmwgIx8X75Dlmtpb4OLKjWoa8G+lQ8=,iv:v+MCyQoAh3IypDSj9ULhMildg5pPVcD6dXp37AO/2KM=,tag:JXcPumO8mfeshlIwvS60OQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
