apiVersion: v1
kind: Secret
metadata:
    name: usage-env
    namespace: usage
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:WBnh1ihyvMGIE5s=,iv:cAVaGxLzL4QJMQab3/4dwkDzBYY9+DFyFmnTP5Hz0Dg=,tag:qBAKqFhpLCExgwKLkusmxA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:wsTvGw==,iv:VMtnBDEKtHkJdQxx8BiA8x5zJUWs8SUhg18WRzbH1PY=,tag:d3N5p03CkIOu1ziT1jHoVA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:nmLSaMvGsg==,iv:qO+PJ+5lF96FeyGLe68k44X6Qp1Po5EtHZAO9PdE/bE=,tag:MCM4s8QXdXULCxAKIo9XSg==,type:str]
    DB_USER: ENC[AES256_GCM,data:1+Ou6pfoaw==,iv:4WRoHp+exM+sZX9tDzLLTEIKyight4Q8aRVZD1ZCxJs=,tag:VDv7tIF68ZoitCHoeYaxlQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jYS7t33ps7SraVg9JG2Aeg8QskZmJXaK+RoOqqyPHYc=,iv:8M3AsfwtryxQFE7GPR5nhSjtqtmTayu1mFRWkTFLvOM=,tag:svuiL3cksv9sbIPX2aA9Sg==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT1FpT2J5US91RUJFc0Vy
            S21PNEtYTlVGRHo1MW9aRUl1NXBVNVhUZ2tFCkVhV1VEVkF2WEp2b2lET3RPWGNM
            TldVMnVJWTdJZE1XOGV4dFU0cVdyVm8KLS0tIGhCQmt3U1B5aGZjNEExQWlhZ0pG
            ZG4rN3BsUkcvdXFGZ2U5RU5tVTRoUHMKowYEnYJHdEVBHYZANfJAyGNEQXfMNKqY
            zFi42grD7+OFbySVF03tLkHOP4Zr1LGIM6NSgqWpCNrm97GlPnbVkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T10:31:55Z"
    mac: ENC[AES256_GCM,data:b5jB6hjMRcaWv/OUejkA8FmH0SzhbMLhXXO9N5lMOh9uR7tPxMuucWme7kL0F49s2aNZBO1hI5o+0L4YKsOeaPnAgCk05m8PMeLqC08gXdQkH3sez45ONvPa+RnJFIShTuxUMk90xxIz0kmwlNqxnrw4rpYr7Lv9Fi8/L3h41sY=,iv:Yy+t8xYJ2mePaWndW2hfO7xfzrsIL34AgYxH7MsMPdA=,tag:1sptogIzW9Q8J/wvRtYMLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
