apiVersion: v1
kind: Secret
metadata:
    name: wordle-env
    namespace: wordle
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:OI31fg==,iv:NPxXiyn6QCpH61ufGOZWETjSkMz/S6GUy+gT+kFfQBw=,tag:EYGOR2fBvwzX8mZ3Lr0OwQ==,type:str]
    APP_ORIGIN: ENC[AES256_GCM,data:7HzGarQnxu+2sU0R2VGjYYJ1fQo33fb3eNp0YQ==,iv:s5JZmZie/FrTu7sSyJAEXs04I3wKxR3kmF1fOQECCsI=,tag:lbvxPTqJ/uiHpzY5mFpb1g==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:TjnUUFHpcgxp051lK6Dask1IcrIN/LD5g23+flimQIK6jv80rgyabb8NK5Lx/cj858mjLw==,iv:AlvNWCiiL6TO6KTXRwGiBh47iz8C5PLfixRY5ns/TjU=,tag:hsFhK7kTAxEA/bBelUQ+Rw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:cH6uiMcHibyAm+ibVttkBeSunBLXJyCBlFZsY3mvspVpY05ZfnqVww==,iv:tRTIa6/LLIVAdKb5AVJesKHPvapLeDcEXo/BuMfXYzw=,tag:74ZMC3dU6LrcdhTQ54WChA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:E4S69XUizeArKTGCvwkTpZyrGE2JC+Lk7PYLEcXvz8qwt0xyUMAgP/LFzwYum4S1JWMTHDTH3FlJilDQpjANtyu0TxA63sHu2WmOZ+r7uWPZ9WQWYna3YXpurIc5L4aZrYcr6CUUIj9HfaLvjx/j0RYljXNbcImos/w7WIQXaiA=,iv:hHVPSflBlXIQwCSp6jpTFnYKOXenTXoYgjsXJt2+Xxw=,tag:ZAxfTOzQUOz4MXind11iWA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:Iko37a9l7G3yiXcZ9djWJYGjvQyBOsplcqhM4vaBaRxIrgCOG8p+DVpB0Tr6FCQpJCnUMqZTA4IlLBq4kdeezA==,iv:4idyPkLV3DNsk9304BZznqQiYv7yO4YNY1/GwygPr18=,tag:LF7aCXZ0VFQrqplkQPQjcQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:adXBWOsiOX/L23j29FtypcPW9Ltf7sRuCyMbxDqc43D38Jpp3Uepk1kD/lVs9dCpeEa69/45saGqXXbBZDcQN5id,iv:14/hwkOs7Kb16Eqr0EufldlHjliY/ecnS5boYM4wygE=,tag:cU9hfILX2UKmWe5GieRDeg==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalg1azJMb0o0STIwVlhy
            a1lZY3pFbmRQK1N3cFpEZmd0MGF0c1JYNTNJCmN6dnJPdXRmcms4UVJZS0FGOCt2
            UUQxMXB6WjlOSVlPOVFMQlhESi8yT28KLS0tIFNWK3Z5ckFTdTJ3MVVSdzRvdFRE
            V1QyQ3JCVUp6bjBuRkVRalprZVA5bEUKJj0CnlG27mXSv/ouSMpVwf8iFMC6FERP
            F8X2jOE2txco5JQcGtcwn7Xf/gDUk3DM1RZ9HGfiK6WdZu2OnPQSKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T11:45:38Z"
    mac: ENC[AES256_GCM,data:DulRTUkhgsP1zTj/tgIiPCJqlHFAnYU6Dov7S9XtA5VdiIWRqnE+aDhgnbeHFYE6H8+A0DXA9cqJSNa1PLxFBigkon0vnvzx6YlkyI1Aj2VCFpIWR5/F0iYfdcKl286saKwTv9FDCqKW0AH2Cdb8kGm96HI0uNke4nMKMXtOuVA=,iv:d5VqUZoauJOcyWQFTRvvWUF/9CchBTtkTRAFYwqSnP0=,tag:Q/JwXSpNvfCMg0smAZC6vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
