apiVersion: v1
kind: Secret
metadata:
    name: dinner-env
    namespace: dinner
type: Opaque
stringData:
    DINNER_API_BASE: ENC[AES256_GCM,data:5sivSPBLd8W9IUMrF7wczKfb7bkiBwRuQCpAS1s=,iv:7I5aGWoEav9/5a92e6LAP/Knh6vMA/FGNR5s4C1rqF8=,tag:+F1npcWFpZNV0/bI/KiP5g==,type:str]
    DINNER_API_KEY: ENC[AES256_GCM,data:6yxmsYkMwhPfGTr39O9hWBixqJ5AMPHCqwx+JVFUuxzzG6JcvMkw8esE0Sp4jMw+PNwnh5fGB9WHNqWfKW3pbQ==,iv:0KvCAZCdSbmnhSwUxLduV0bzwt6gKNAFhsIF8DPvu7s=,tag:Q99tEboGaJMsfZCmv2wm6Q==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZHBJMmtqd3d4UytxUU1G
            SFBPTGZ6Y3ROenBpczdOZjh1eDhtZTFrWms4CkcrcGhyZDV5YlIrVlorU29tT0RR
            TCtMRjk3V0o2dWtabW9MYXNTeXRrazQKLS0tIGZhekFySHZmUDBqWExzVUdsQUhP
            VmRVMUV0UC9hMUV3YlE0aDVZcTNSb3MKWYXxwtX4ihKuNeEtXtn/JA2P68Io7Ekj
            I0TP7AWWSzfzXAEKrChxPn6lFB7/JFYoFpkUOZsKgDJxPY1f/Su0bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T01:04:51Z"
    mac: ENC[AES256_GCM,data:NBkEsu1A2OCaa/YH1UqudVFitkMl9Drl/OuRFNZxhvsbAExlc02/U1LqgUwWY43SGavqQNc+OHB3NeURIwR4/FlNJOsDJI259xeJcmYakn0Njc26nVQ0l5enEYuajOdvtee1FGPfKwRfwIO/1OxRjYswttCbQu5592+sZ+xsBWM=,iv:K+ARg4pivwb26VYPwIZJde2znFr4JCmKbOQW4bKpJL4=,tag:W1u4gJM0jWR76RMRhuIJsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
