apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - database-service.yaml
  - database-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - guacd-service.yaml
  - guacd-deployment.yaml
  - server-service.yaml
  - server-deployment.yaml
  - ingressroute.yaml
  - certificate.yaml
