apiVersion: v1
kind: Secret
metadata:
    name: patchmon-env
    namespace: patchmon
type: Opaque
stringData:
    CORS_ORIGIN: ENC[AES256_GCM,data:dA9CZ1oTijfLYGo5JqP8/PgMVyTiVk3P0wu579R9,iv:xnsMoRrcKIVLbiVGQqnCIv0Po7m5NSAp029hHNUBpQM=,tag:dRAnddqANqGAikGWXOxyzA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:vcyuZfMFOXV+CDutx+AHPa/GMXLrr+6Xa2BPiKQPfN4=,iv:qbkWRoX5Mt2PmHjEeF5/ctln9sGEGaQdP9QJex+iJHE=,tag:Zafn0GlfPdrHZjUhoUwcsA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:lcAnQyIxAfU=,iv:gZUGHIrfE5C++p0VDAtsq5+wZ3Af0efumZuWZktQ6D0=,tag:mqH56eHL9hBBkRRTW1jPBA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+EPU+3ShPSzmNB+39uL+IgRnULyDN7qR818cR+WWmxE=,iv:GvpTfL+r+A32X4fbgARdFUrC2ugU7mF37VkJRC5bvns=,tag:zn+HNyW07YdgiUeVZkqqUA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fhRkT5aLoEwlxlhWCw==,iv:S+1AhF3UhYr9i1HVSkTPE2jr/ZQPeccVe0HgmFG2ibU=,tag:CVaUTGnFoxcK33SlWraiZA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Cfus0vECsBiB1Ns=,iv:J0EySqyhcAYe6YkR/4PTVtrRWZxM+AP/ew+UDOaPY/A=,tag:hI9hMZp1MyYtxBBEpBBpBQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3b2rMPESm4ppeBU03ZuvTAR8pZCwdRFWqtuZBhfJIBoXa0bl611gZuZriG5AE62fLf6sNg1AYW9PW2eUagTn9nJTKZYoURjZRk/5+RGlwByzpqkOhw==,iv:MX+y/BOOsrD3jGeXIhb0rOLATLXvqmeRAtD+2waB0E8=,tag:jVulcdlVm/jOTZ5cg301uQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:I4tsTs8=,iv:LHLvyVw7oaIxs2XwppX8dhEJ04kBz70lLEzDkhci2ME=,tag:3B5RiOj4P7F/N3yZ0FUJtA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:p3oZ8w==,iv:2EtIExnQqhnxeaD4SlLQQqBxjGG7PlzWsWsZa+m4Zk8=,tag:c64v9XE8nzFZbbCJ26X3gA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:PthxTU8sZBPLedXvkXVvBjB3dd05TFh5oAl0YIURfSc=,iv:OI+EsTFMQKV8c/La3XumykI6UNFiLUVdxM0YqXZ+Yos=,tag:y82C3dts6gHRkp+y0UBbgA==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:iw==,iv:3TO2+gaCkVQcksiPxCxwowNoGaSVdrxM4AFxtWzAjnM=,tag:odMU6bJYNvR+/CogKwl63Q==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:YJzNMP+P71JVIqfbqTNnwb82Enjn3ajcNseUfGyMbqY=,iv:fGXxZH0sXPUe+c3JzpvP6RsBNaBIDRRPiNJ+jmmsmdA=,tag:Xht2RqHEgs5E5nnAWL50vQ==,type:str]
    AI_ENCRYPTION_KEY: ENC[AES256_GCM,data:cTebPlcWRxh36iKvYt1QIhZhe/ugs2QQ9XtcJ3u6358=,iv:FiRRE8OhTJsI43Dr0aLh3GaTSnxxj0MXxV0rAQ2plWQ=,tag:UUqbocyzzxEy79tjj1nkwg==,type:str]
    GUACD_ADDRESS: ENC[AES256_GCM,data:xQ85oNSlmVesgw==,iv:t2KAyeuiRWaeUQQICsc3eT1qLsl1d14Wga0FiBQdoo8=,tag:C+3eHHh+x5Jr2oLvnkSADQ==,type:str]
    TRUST_PROXY: ENC[AES256_GCM,data:yA6v/w==,iv:/xvarZKWl5dKTT9OK3eSzmwOVRKt2tdJy1wg9t1I4eI=,tag:pDn1qoEkYBvh6vIF/5eOTQ==,type:str]
    APP_ENV: ENC[AES256_GCM,data:UlU3GPt5hsOx9w==,iv:MiqfieH9e+7EcAUGKjd22omoqw5taTs7CpcrdYM6cBk=,tag:6HwVJ8O6Icjc8M42/q7JNQ==,type:str]
    TZ: ENC[AES256_GCM,data:YEfS97DtAVqd60vJaH7C9Q==,iv:N3anQeEmOSasaYtfXpurYl2gXdI4VWqgL0nM0rkZmV0=,tag:nrofHGN5KRtbRzYi6QIdlw==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMHJraE5IV3gyZm1KUGMv
            ZHNHMzFuS21GUkx2aTc5Z1ArRll0MFNiNW1jCldtMmtzQzNlUXdMSEd5ZE1nMlAv
            dDlYVzQ1czBKNHMxWFREbUVicVlmT3cKLS0tIHpsNyszZWFJUjhLQWF4eVN1M2ND
            amhyNVZlZElxVEdDcXo2NWdXNlM1TGsK4BNEY2VgJo01dsjWLPZj2UkpeXvI0J1/
            4DNd5t+rs2tshuyTd6TdoZO/nUOpfzvzR0PzMKPZ0TXdAe0wj3BPSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T23:01:16Z"
    mac: ENC[AES256_GCM,data:bM82YfsKHduLmOAOSjupQ1ata8DwTaRuodrSSSmuwbFWxwiSR0kZpX1uf0gHuj9sn31kKy07KDjkLbkCmpWiDcnpGWt0/M4DQCf3uF17UrQ+Pss98zX9SBJm1yy09AlTfIVvvfqNGVV3VXkeZYN3jKYGhzU+CNJQBwwAM6Vn6iY=,iv:hh1LlIZUxsHMv2ZNLiCU1Hi1l0ac3gXAqGCvwZgxc/c=,tag:EAwwY+TNpw7g5yH+C5v25g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
