apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: api
type: Opaque
stringData:
    HOST: ENC[AES256_GCM,data:ZgyvbfIInQ==,iv:9mfSzAyOlKjFYzOW1AjZ2gJqwkhd35rruhi33bMKCzU=,tag:K3YxjYu3T/WUQj+0kPiiPg==,type:str]
    PORT: ENC[AES256_GCM,data:MK1bvQ==,iv:YILhxb9Reno8RIBl2JRfLCt0MeyWM2BzyaG78JGGsgQ=,tag:p4jOnoP0DbYl/GUSBOapLw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:1idv4TcGpsZ6vtA=,iv:D8JaFEQIuJd5dZO/cErp890SFAzkVNcgw7ZBczd5m7w=,tag:aKv9l1cIXx6mQ4lldilJFw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:oeBhow==,iv:ORZbcYm6oYe8ODapgwLvjQ5xwShYBohLnnwxb+RV66M=,tag:HZhFVYPpM+weDSS5vC0mUw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:2FtLiKPg2rzHZg==,iv:pklmItPqP8DImmaflvfV3M0NW0ZITPFewhqc4FeXjKM=,tag:RVdZeMw0FhfDwicgPNROeA==,type:str]
    DB_USER: ENC[AES256_GCM,data:3SXZLZeoByc=,iv:8hNplQn1tPo9NBrE4q6s4MR00yV/V0oVFu+oBfkgirc=,tag:Wz/qgoRSLzubrLzgcBoAjA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:BSK18EzehxdOGcRIbuk=,iv:tXx4yYg8usI7WCNVnpaizbSn6P8JC5g+yb21VpJT+VI=,tag:uD/YAVBjwrI0/AQ18iChfA==,type:str]
    GOOGLE_CALENDAR_ID: ENC[AES256_GCM,data:L+guvpf6Cwc5TuKMAnwo44cCICmyfbw3/32/MsjsJ3jcwTqjWKU/N+JEXo5W2SetmgtDxw==,iv:EykwknmSsCg6Tg9dpphsGozAVXJWzdzEzLXQ4gxs6GA=,tag:/LZUCwtZEF7bXKHVupqEDQ==,type:str]
    GOOGLE_SERVICE_ACCOUNT_JSON: ENC[AES256_GCM,data:MQE=,iv:MH07UgvAqF2nEqj7HTaqsQm9TkVNzqvnFCVA8btQFCI=,tag:vcvzf7jQssUgqN28Na0jmA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:wYtv/IU8RRsFWaurNGuvKXexhg==,iv:musK6XAHNJ6lbQjfTgB9Mqc8Je81yq1uAQ/kakSbrcQ=,tag:6TWtrmgdQcwdqgnV1eKR8A==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:OvvWGA==,iv:pV9OiW46uNjpUfw57HOEdvQOcAstpMBffDHTYBpUXe8=,tag:3g11xtgJFx02aijxDHpQvQ==,type:str]
    REDIS_USERNAME: ""
    REDIS_PASSWORD: ENC[AES256_GCM,data:MYPlXXIC6Heub9+PEhqzO67ZR0IkNr6w4qcCbwVEzg0=,iv:31m92y94xIHWKFTi/0GkOHNpf7s6hhjmZGQXjTf8yh4=,tag:SaGXOC6gF1xIW4peb6CFxg==,type:str]
    NOTION_TOKEN: ENC[AES256_GCM,data:1v+jYliJTbvgz8pkNi1meiBdSxYQDW1t9a4PaGD3cvuzqxM86XY9AqoVLCp+ufP3xQ0=,iv:/yFPuiS+KDeLVD2ktT9qsLdmsQmo7AwxMBZtCjVrg0U=,tag:UT5PwRTDLChWfQsfFcN8ww==,type:str]
    NOTION_REFLECTIONS_DB_ID: ENC[AES256_GCM,data:Fny6bPLHG3YVAVvh+kafFdyl4vLtFsz51q/HWt+36iY2vu/8,iv:xSlJEsxiwhak3QPlq/OTKVFKH86Ly8MggUPwnNGETaU=,tag:2A2lNbwbBiAEf8SXZIN/5w==,type:str]
sops:
    age:
        - recipient: age18j6zrhuukf8tuemyt9xzj0plfxzadtzfqjncmufhspptsl67hp2qjmj56n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVlhZdVlWVmZUUm1vVWV2
            a2NOcWFQSTU4MithZ0dTaGJEMXQzUlM0SkFrCjZmbnprYXdualJYQWI1T0pnUGFH
            R09TMCt4T29lWFh4NWxQQ2NPdXo0ckkKLS0tIEhpNHpGTlF1Y0dDdUpjRXhwODE4
            MUNXaUpHaEVyZitKNlV5RnhVdUprOGMKFnn6EpNKP9O3fhT4JQv7+wKUMki+tysX
            DO154VNHPvDFebp9rRc7yqat9sWETeTH+mFOOATgjzeQy8iVvSgiFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T04:08:25Z"
    mac: ENC[AES256_GCM,data:eWa9cy8/5HMj/a6LbcR4tHGeiizm5jdSgcR7jMrNM2gE+Ggs93okiklFWvgYSJ4oMGMwEP8fyHaZNL5naK0tFRBD9BR3wR+v9GF5mbTQxhsg6s6ry+bitm2W/sluhCrFpIdnsL1qKjFjU36NKwbdfgWdVvyDmo1Glz7f0Z0v+c0=,iv:9J92NxKQ9vKlEKdqouRKjZ/XqL2Taa4oyHEte3bWUFg=,tag:A44jNdlolpm9G/XdZlOjDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
